services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'springboot'
      MYSQL_USER: 'springboot'
      MYSQL_PASSWORD: '5FjGSUZn7R8qW6jnthT8BwwHZV2Gyy'
      MYSQL_ROOT_PASSWORD: 'unife2024'
    expose:
      - '3306'
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    networks:
      - jarvis-net

  mock:
    build: ./Mock
    expose:
      - '3000'
    networks:
      - jarvis-net

  backend:
    build: ./JARVIS-backend
    expose:
      - '8080'
    depends_on:
      - db
      - mock
    networks:
      - jarvis-net

  frontend:
    build: ./JARVIS-frontend
    ports:
      - '80:5173'
    depends_on:
      backend:
        condition: service_started
    networks:
      - jarvis-net

networks:
  jarvis-net:
    driver: bridge
